name: serverless-scheduler-dev

on:
  push:
    branches:
      - '*'
      - '!main'

env:
  SERVICE_FOLDER: .
  NODEJS_VERSION: 14.x

jobs:
  deploy:
    name: ServerlessSchedulerDev
    runs-on: ubuntu-latest
    concurrency: ServerlessSchedulerConcurrencyGroupDev

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      DEV_ACCOUNT_ID: ${{ secrets.DEV_ACCOUNT_ID }}
      NEXTAUTH_SECRET: ${{ secrets.DEV_NEXTAUTH_SECRET }}
      CORE_API_KEY: ${{ secrets.DEV_CORE_API_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODEJS_VERSION }}

      # Other steps here include npm install, linting, unit tests, etc
      # Run npm install to get dependencies and make sls available on the path
      - run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Deploying to stage: dev'
        uses: './.github/actions/sls-deploy'
        with:
          service-folder: ${{ env.SERVICE_FOLDER }}
          stage: dev
          aws-account-id: ${{ env.DEV_ACCOUNT_ID }}
          next-auth-secret: ${{ env.NEXTAUTH_SECRET }}
          core-api-key: ${{ env.CORE_API_KEY }}